namespace HSDRawViewer.GUI.MEX
{
    public class DefaultItemNames
    {
        public static string[] CommonItemNames = {"Capsule",
"Box",
"Barrel (Taru)",
"Egg",
"Party Ball (Kusudama)",
"Barrel Cannon (TaruCann)",
"Bob-omb (BombHei)",
"Mr. Saturn (Dosei)",
"Heart Container",
"Maxim Tomato",
"Starman (Super Star)",
"Home-Run Bat",
"Beam Sword",
"Parasol",
"Green Shell (G Shell)",
"Red Shell (R Shell)",
"Ray Gun (L Gun)",
"Freezie (Freeze)",
"Food",
"Proximity Mine (MSBomb)",
"Flipper",
"Super Scope (S Scope)",
"Star Rod",
"Lip's Stick",
"Fan (Harisen)",
"Fire Flower (F Flower)",
"Super Mushroom (Kinoko)",
"",
"",
"Warp Star (WStar)",
"Screw Attack (ScBall)",
"Bunny Hood (RabbitC)",
"Metal Box (MetalB)",
"Cloaking Device (SpyCloak)",
"Poké Ball (M Ball)",
"Ray Gun recoil effect",
"Star Rod Star",
"Lips Stick Dust",
"Super Scope Beam",
"Ray Gun Beam",
"Hammer Head",
"Flower",
"Yoshi's egg (Event)",};

        public static string[] FighterItemNames = {
"Goomba (DKuriboh)",
"Redead (Leadead)",
"Octarok (Octarock)",
"Ottosea",
"Stone(Octarok Projectile)",
"Mario's fire",
"",
"Kirby's Cutter beam",
"Kirby's Hammer",
"",
"",
"Fox's Laser",
"Falco's Laser",
"Fox's shadow",
"Falco's shadow",
"Link's bomb ",
"Young Link's bomb",
"Link's boomerang",
"Young Link's boomerang",
"Link's Hookshot",
"Young Link's Hookshot",
"Arrow",
"Fire Arrow",
"PK Fire ",
"PK Flash ",
"PK Flash",
"PK Thunder (Primary)",
"PK Thunder",
"PK Thunder",
"PK Thunder",
"PK Thunder",
"Fox's Blaster",
"Falco's Blaster",
"Link's Arrow",
"Young Link's arrow",
"PK Flash (explosion)",
"Needle(thrown)",
"Needle",
"Pikachu's Thunder ",
"Pichu's Thunder",
"Mario's cape",
"Dr.Mario's cape ",
"Smoke (Sheik)",
"Yoshi's egg(thrown) ",
"        Yoshi's Tongue??",
"Yoshi's Star ",
"Pikachu's thunder (B)",
"Pikachu's thunder (B)",
"Pichu's thunder (B)",
"Pichu's thunder (B)",
"Samus's bomb",
"Samus's chargeshot ",
"Missile ",
"Grapple beam",
"Sheik's chain",
"",
"Turnip ",
"Bowser's flame",
"Ness's bat      ",
"Yoyo",
"Peach's parasol",
"Toad    ",
"Luigi's fire    ",
"Ice(Iceclimbers)",
"Blizzard        ",
"Zelda's fire",
"Zelda's fire (explosion)",
"",
"Toad's spore    ",
"Mewtwo's Shadowball",
"Iceclimbers' Up  ",
"Pesticide",
"Manhole",
"Fire(G&W)",
"Parashute",
"Turtle",
"Sperky",
"Judge",
"",
"Sausage",
"Milk (Young Link)",
"Firefighter(G&W)",
"Masterhand's Laser",
"Masterhand's Bullet",
"Crazyhand's Laser",
"Crazyhand's Bullet",
"Crazyhand's Bomb",
"Kirby copy Mario's Fire (B)",
"Kirby copy Dr. Mario's Capsule (B)",
"Kirby copy Luigi's Fire (B)",
"Kirby copy IceClimber's IceCube (B)",
"Kirby copy Peach's Toad (B)",
"Kirby copy Toad's Spore (B)",
"Kirby copy Fox's Laser (B)",
"Kirby copy Falco's Laser (B)",
"Kirby copy Fox's Blaster (B)",
"Kirby copy Falco's Blaster (B)",
"Kirby copy Link's Arrow (B)",
"Kirby copy Young Link's Arrow (B)",
"Kirby copy Link's Arrow (B)",
"Kirby copy Young Link's Arrow (B)",
"Kirby copy Mewtwo's Shadowball (B)",
"Kirby copy PK Flash (B)",
"Kirby copy PK Flash Explosion (B)",
"Kirby copy Pikachu's Thunder (B)",
"Kirby copy Pikachu's Thunder (B)",
"Kirby copy Pichu's Thunder (B)",
"Kirby copy Pichu's Thunder (B)",
"Kirby copy Samus' Chargeshot (B)",
"Kirby copy Sheik's Needle (thrown) (B)",
"Kirby copy Sheik's Needle (ground) (B)",
"Kirby copy Bowser's Flame (B)",
"Kirby copy Mr. Game & Watch's Sausage (B)",
"(unique)",
"Yoshi's Tongue?? (B)",
"(unique)",
"Coin",
"0xA0      ", };

        public static string[] PokemonItemNames = {
"Goldeen (Tosakinto)",
"Chicorita ",
"Snorlax",
"Blastoise",
"Weezing (Matadogas)",
"Charizard (Lizardon)",
"Moltres",
"Zapdos",
"Articuno",
"Wobbuffet",
"Scizor",
"Unown",
"Entei",
"Raikou",
"Suicune",
"Bellossom (Kireihana)",
"Electrode (Marumine)",
"Lugia ",
"Ho-oh",
"Ditto (Metamon)",
"Clefairy",
"Togepi",
"Mew",
"Celebi",
"Staryu (Hitodeman)",
"Chansey",
"Porygon2",
"Cyndaquil (Hinoarashi)",
"Marill",
"Venusaur (Fushigibana)",
"Chicorita's Leaf",
"Blastoise's Water",
"Weezing's Gas",
"Weezing's Gas",
"Charizard's Breath",
"Charizard's Breath",
"Charizard's Breath",
"Charizard's Breath",
"Mini-Unowns",
"Lugia's Aeroblast",
"Lugia's Aeroblast",
"Lugia's Aeroblast",
"Ho-Oh's Flame",
"Staryu's Star",
"Healing Egg",
"Cyndaquil's Fire",
"", };

        public static string[] StageItemNames = {
"Old Goomba (Old-Kuri)",
"Target (Mato)",
"Shyguy (Heiho)",
"Koopa(Green) (Nokonoko)",
"Koopa(Red) (PataPata)",
"Likelile",
"Old Redead (old-lead) [invalid]",
"Old Octorok(old-octa) [invalid]",
"Old Ottosea (old-otto)",
"White Bear (whitebea)",
"Klap",
"Green Shell (zgshell)",
"Red Shell (green act) (zrshell)",
"Tingle (on balloon)",
"[Invalid]",
"[Invalid]",
"[Invalid]",
"Apple",
"Healing Apple",
"[Invalid]",
"[Invalid]",
"[Invalid]",
"Tool (Flatzone)",
"[Invalid]",
"[Invalid]",
"Birdo",
"Arwing Laser ",
"Great Fox's Laser ",
"Birdo's Egg"
        };
    }
}
